### ISSUE TITLE
国内镜像源都关闭了，麻烦开发者更新下镜像源地址

### ISSUE THREAD

**Issue by Nanqiang01** [117503445/flow-pdf#11]

**Comment by 117503445** [comment]
镜像在 `117503445/flow-pdf` 和 `registry.cn-hangzhou.aliyuncs.com/117503445-mirror/flow-pdf` 都是同步更新的。你如果无法访问 DockerHub 上的 `117503445/flow-pdf`，那么使用阿里云的 `registry.cn-hangzhou.aliyuncs.com/117503445-mirror/flow-pdf` 即可。
