### ISSUE TITLE
Turns into a two-column layout when translation is enabled

### ISSUE THREAD

**Issue by 117503445** [117503445/flow-pdf#4]

**Comment by 117503445** [comment]
@wsyzzz 开发好了，你可以看一下效果

对于已经上传过的 PDF，你可以再上传一次，然后在网页中 Ctrl F5 刷新缓存，应该就可以看到双页布局了

**Comment by wsyzzz** [comment]
> @wsyzzz 开发好了，你可以看一下效果
> 
> 对于已经上传过的 PDF，你可以再上传一次，然后在网页中 Ctrl F5 刷新缓存，应该就可以看到双页布局了

很赞的效果~期待摘要翻译的feature
